import { wordpressBase } from './backend';
import { env } from '$env/dynamic/private';
import type { Cookies } from '@sveltejs/kit';
import type { SmartMetadata } from '$lib/smart-shopping';

export type Prices = { price: string; currency_code: string; currency_minor_unit: number };
export type ProductImage = { id: number; src: string; thumbnail: string; alt: string };
export type StoreCategory = { id: number; name: string; slug: string; count: number; image: ProductImage | null };
export type StoreProduct = { id: number; name: string; slug: string; description: string; short_description: string; sku: string; prices: Prices; images: ProductImage[]; categories: StoreCategory[]; is_purchasable: boolean; is_in_stock: boolean; stock_availability: { text: string }; has_options: boolean; inkora_smart?: SmartMetadata };
export type SmartStoreProduct = StoreProduct & { inkora_smart: SmartMetadata };
export type JournalArticle = { id: number; slug: string; title: string; excerpt: string; published_at: string };
export type CartItem = { key: string; id: number; name: string; quantity: number; quantity_limits: { minimum: number; maximum: number; editable: boolean }; prices: Prices; totals: Prices & { line_total: string }; images: ProductImage[]; stock_availability: { text: string } };
export type Cart = { items: CartItem[]; totals: Prices & { total_price: string; total_items: string; total_shipping: string | null; total_tax: string }; items_count: number; needs_shipping: boolean; needs_payment: boolean; shipping_rates: unknown[]; payment_methods: string[]; errors: unknown[] };
const STORE_PATH = '/wp-json/wc/store/v1/'; const cartCookie = 'inkora_cart_token';
function baseUrl() { const url = wordpressBase(); if (!url) throw new Error('Store backend unavailable'); return url; }
function testSlug() { return env.INKORA_TEST_PRODUCT_SLUG || 'inkora-phase-01-test'; }
function isPrices(v: any): v is Prices { return typeof v?.price === 'string' && typeof v?.currency_code === 'string' && Number.isInteger(v?.currency_minor_unit); }
function isCurrency(v: any) { return typeof v?.currency_code === 'string' && Number.isInteger(v?.currency_minor_unit); }
function image(v: any): ProductImage | null { return Number.isInteger(v?.id) && typeof v?.src === 'string' ? { id: v.id, src: v.src, thumbnail: typeof v.thumbnail === 'string' ? v.thumbnail : v.src, alt: typeof v.alt === 'string' ? v.alt : '' } : null; }
function category(v: any): StoreCategory | null { return Number.isInteger(v?.id) && typeof v?.name === 'string' && typeof v?.slug === 'string' && Number.isInteger(v?.count) ? { id: v.id, name: v.name, slug: v.slug, count: v.count, image: image(v.image) } : null; }
function smart(v: any): SmartMetadata | undefined { const groups = ['machine', 'needle', 'ink']; const levels = ['beginner', 'intermediate', 'professional']; if (v?.schema_version !== '1' || !groups.includes(v?.group)) return undefined; const result: SmartMetadata = { schema_version: '1', group: v.group }; if (levels.includes(v.skill_level)) result.skill_level = v.skill_level; if (Array.isArray(v.supported_styles) && v.supported_styles.every((x: unknown) => typeof x === 'string')) result.supported_styles = v.supported_styles; if (Array.isArray(v.techniques) && v.techniques.every((x: unknown) => typeof x === 'string')) result.techniques = v.techniques; if (v.specifications && typeof v.specifications === 'object' && !Array.isArray(v.specifications)) result.specifications = v.specifications; return result; }
function product(v: any): StoreProduct | null { if (!Number.isInteger(v?.id) || typeof v?.name !== 'string' || typeof v?.slug !== 'string' || !isPrices(v?.prices) || !Array.isArray(v?.images) || !Array.isArray(v?.categories)) return null; const p: StoreProduct = { id: v.id, name: v.name, slug: v.slug, description: typeof v.description === 'string' ? v.description : '', short_description: typeof v.short_description === 'string' ? v.short_description : '', sku: typeof v.sku === 'string' ? v.sku : '', prices: v.prices, images: v.images.map(image).filter(Boolean) as ProductImage[], categories: v.categories.map(category).filter(Boolean) as StoreCategory[], is_purchasable: v.is_purchasable === true, is_in_stock: v.is_in_stock === true, stock_availability: { text: typeof v?.stock_availability?.text === 'string' ? v.stock_availability.text : '' }, has_options: v.has_options === true }; const metadata = smart(v.extensions?.inkora_smart); if (metadata) p.inkora_smart = metadata; return p; }
function cleanProduct(v: any) { const p = product(v); return p && p.slug !== testSlug() ? p : null; }
async function getJson(path: string, init: RequestInit = {}) { const response = await fetch(new URL(path, baseUrl()), { ...init, signal: AbortSignal.timeout(10000), headers: { Accept: 'application/json', ...init.headers } }); const payload: unknown = await response.json().catch(() => null); if (!response.ok) { const msg = typeof (payload as any)?.message === 'string' ? (payload as any).message : `Store API HTTP ${response.status}`; throw new Error(msg); } return { payload, response }; }
export async function getProducts(filters: { search?: string; category?: string } = {}) { const url = new URL(STORE_PATH + 'products', baseUrl()); url.searchParams.set('per_page', '12'); if (filters.search) url.searchParams.set('search', filters.search.slice(0, 100)); if (filters.category) url.searchParams.set('category', filters.category); const { payload } = await getJson(url.pathname + url.search); if (!Array.isArray(payload)) throw new Error('Invalid product response'); return payload.map(cleanProduct).filter(Boolean) as StoreProduct[]; }
export async function getSmartProducts(): Promise<SmartStoreProduct[]> { const url = new URL(STORE_PATH + 'products', baseUrl()); url.searchParams.set('per_page', '100'); const { payload } = await getJson(url.pathname + url.search); if (!Array.isArray(payload)) throw new Error('Invalid product response'); return payload.map(cleanProduct).filter((p): p is SmartStoreProduct => !!p && p.is_in_stock && !!p.inkora_smart); }
export async function getReviewedJournalArticles(): Promise<JournalArticle[]> { const { payload } = await getJson('/wp-json/inkora/v1/journal?per_page=12'); const articles = (payload as any)?.articles; if (!Array.isArray(articles)) throw new Error('Invalid journal response'); return articles.filter((article: any): article is JournalArticle => Number.isInteger(article?.id) && typeof article?.slug === 'string' && typeof article?.title === 'string' && typeof article?.excerpt === 'string' && typeof article?.published_at === 'string'); }
export async function getProduct(slug: string) { const url = new URL(STORE_PATH + 'products', baseUrl()); url.searchParams.set('slug', slug); url.searchParams.set('per_page', '1'); const { payload } = await getJson(url.pathname + url.search); if (!Array.isArray(payload)) throw new Error('Invalid product response'); return cleanProduct(payload[0]); }
export async function getCategories() { const { payload } = await getJson(STORE_PATH + 'products/categories'); if (!Array.isArray(payload)) throw new Error('Invalid category response'); return payload.map(category).filter((c): c is StoreCategory => !!c && !(c.slug === 'uncategorized' && c.count <= 1)); }
export async function getTestProduct(): Promise<StoreProduct | null> { const url = new URL(STORE_PATH + 'products', baseUrl()); url.searchParams.set('slug', testSlug()); url.searchParams.set('per_page', '1'); const { payload } = await getJson(url.pathname + url.search); if (!Array.isArray(payload)) throw new Error('Invalid product response'); return product(payload[0]); }
function cart(v: any): Cart { if (!Array.isArray(v?.items) || !isCurrency(v?.totals) || typeof v.totals.total_price !== 'string' || !Number.isInteger(v?.items_count)) throw new Error('Invalid cart response'); const items = v.items.map((i: any): CartItem | null => { if (typeof i?.key !== 'string' || !Number.isInteger(i?.id) || typeof i?.name !== 'string' || !Number.isInteger(i?.quantity) || !isPrices(i?.prices) || !isCurrency(i?.totals) || typeof i.totals.line_total !== 'string') return null; return { key: i.key, id: i.id, name: i.name, quantity: i.quantity, quantity_limits: { minimum: Number.isInteger(i?.quantity_limits?.minimum) ? i.quantity_limits.minimum : 1, maximum: Number.isInteger(i?.quantity_limits?.maximum) ? i.quantity_limits.maximum : 9999, editable: i?.quantity_limits?.editable !== false }, prices: i.prices, totals: { ...i.totals, price: i.totals.line_total, line_total: i.totals.line_total }, images: Array.isArray(i.images) ? i.images.map(image).filter(Boolean) as ProductImage[] : [], stock_availability: { text: typeof i?.stock_availability?.text === 'string' ? i.stock_availability.text : '' } }; }).filter(Boolean) as CartItem[]; return { items, totals: { ...v.totals, price: v.totals.total_price, total_price: v.totals.total_price, total_items: typeof v.totals.total_items === 'string' ? v.totals.total_items : '0', total_shipping: typeof v.totals.total_shipping === 'string' ? v.totals.total_shipping : null, total_tax: typeof v.totals.total_tax === 'string' ? v.totals.total_tax : '0' }, items_count: v.items_count, needs_shipping: v.needs_shipping === true, needs_payment: v.needs_payment === true, shipping_rates: Array.isArray(v.shipping_rates) ? v.shipping_rates : [], payment_methods: Array.isArray(v.payment_methods) ? v.payment_methods.filter((m: unknown): m is string => typeof m === 'string') : [], errors: Array.isArray(v.errors) ? v.errors : [] }; }
export async function requestCart(cookies: Cookies, path = 'cart', init: RequestInit = {}) { const headers = new Headers({ Accept: 'application/json', ...init.headers }); const token = cookies.get(cartCookie); if (token) headers.set('Cart-Token', token); const { payload, response } = await getJson(STORE_PATH + path, { ...init, headers, cache: 'no-store' }); const nextToken = response.headers.get('Cart-Token'); if (nextToken) cookies.set(cartCookie, nextToken, { path: '/', httpOnly: true, sameSite: 'lax', secure: baseUrl().protocol === 'https:', maxAge: 604800 }); return cart(payload); }
